<div>.</div>
<div class="gray-line"></div>
<h2>Comments:</h2>
<?php
//echo '<pre>', var_dump($this->getPost()->getAllowComments()), '</pre>';
//echo '<pre>', var_dump($this->getComments()->getData()), '</pre>';
$comments = $this->getComments();
?>
<?php foreach ($comments as $comment): ?>
    <div class="comment-section">
        <p class="float-right-name"><strong><?= $comment->getName() ?></strong>
            <span><?= $comment->getCreatedAt() ?></span></p>
        <h3><?= $comment->getTitle() ?></h3>
        <p><?= $comment->getComment() ?></p>
    </div>
<?php endforeach; ?>



<?php if ($this->getPost()->getAllowComments()): ?>
    <?php echo $this->getChildHtml() ?>
<?php endif; ?>

